---
- name: installing wildfly in ubuntu 20.04
  hosts: all
  become: yes
  vars: 
    wildfly_version: "22.0.1"
    java: openjdk-11-jdk
    group: wildfly
    owner: wildfly
    user: wildfly
    home_dir: /opt/wildfly
    shell: /sbin/nologin
  tasks: 
    - name: installing java
      ansible.builtin.apt:
        name: "{{ java }}"
        update_cache: true
        state: present
    - name: create a system account for wildfly group
      ansible.builtin.group:
        name: "{{ group }}"
        system: true
        state: present
    - name: create a system account for wildfly user
      ansible.builtin.user:
        name: "{{ user }}"
        group: "{{ group }}"
        system: true
        home: "{{ home_dir }}"
        shell: "{{ shell }}"
        state: present
        create_home: true
    - name: download wildfly tar file
      ansible.builtin.get_url:
        url: "https://download.jboss.org/wildfly/{{ wildfly_version }}.Final/wildfly-{{ wildfly_version }}.Final.tar.gz"
        dest: /tmp
        mode: '0440'
    - name: untaring the tar file
      ansible.builtin.unarchive:
        src: "/tmp/wildfly-{{ wildfly_version }}.Final.tar.gz"
        dest: /tmp/
        remote_src: true
    - name: copy file with owner and permissions
      ansible.builtin.copy:
        src: "/tmp/wildfly-{{ wildfly_version }}.Final/"
        dest: "{{ home_dir }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        remote_src: true
        mode: '0777'
    - name: changing ownership of wildfly
      ansible.builtin.file:
        path: "{{ home_dir }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        recurse: true
        mode: '0777'
    - name: Create /etc/wildfly directory 
      ansible.builtin.file:
        path: /etc/wildfly
        state: directory
        mode: '0777'
    - name: copying files to /etc/wildfly
      ansible.builtin.copy:
        src: "{{  home_dir }}/docs/contrib/scripts/systemd/wildfly.conf"
        dest: /etc/wildfly/
        remote_src: true
        mode: '0777'
    - name: copying files to /opt/wildfly/bin/
      ansible.builtin.copy:
        src: "{{ home_dir }}/docs/contrib/scripts/systemd/launch.sh"
        dest: "{{ home_dir }}/bin/"
        remote_src: true
        mode: '0777'
    - name: Execute the command in remote shell
      ansible.builtin.command: sh -c 'chmod +x /opt/wildfly/wildfly-22.0.1.Final/bin/*.sh'
    - name: copying files to /opt/wildfly/bin/
      ansible.builtin.copy:
        src: "{{ home_dir }}/docs/contrib/scripts/systemd/wildfly.service"
        dest: /etc/systemd/system/
        remote_src: true
        mode: '0777'
    - name: starting wildfly service
      ansible.builtin.systemd:
        name: wildfly.service
        state: started
        enabled: yes
    - name: restarting wildfly service
      ansible.builtin.systemd:
        name: wildfly.service
        state: restarted
        enabled: yes
