pipeline {
    agent { label 'ANS' } 
    stages {
        stage('clone') { 
            steps {
                git url: 'https://github.com/GUDAPATIVENKATESH/Documentation.git',
                branch: 'main'    
            }
        }
        stage('changing directory') { 
            steps {
                sh 'cd ~/Documentation/Intergating anssible with jenkins'
            }
        }
        stage('Deploy') { 
            steps {
                sh 'ansible -i hosts ./playbooks/apache2.yml'
            }
        }
    }
}